import Head from "next/head";
import HomePage from "@/Components/HomePage";
import ForYouPage from "../pages/foryoupage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Summarist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      {/* <ForYouPage /> */}
    </>
  );
}
